/**
 * Umbrella Agent Marketplace — shared types + seed data.
 *
 * Every `AgentListing` is a token backed by the *labor* of a specific Umbrella
 * agent. The price isn't driven by narrative — it's driven by a
 * Performance-Oracle Loop:
 *
 *   mission completes → RelayerService signs a proof →
 *   UmbrellaAgentToken.recordSuccess() → v4 hook adjusts fee & buyback rate
 *
 * Until the relayer + v4 hook are deployed, these listings are generated
 * client/server-side so we can design against the final shape. The JSON schema
 * here is what the real API will return on day one — swap the data source,
 * nothing else.
 */

export type AgentCategory =
  | "research"
  | "trading"
  | "yield"
  | "scraper"
  | "writer"
  | "security";

export type MissionEvent = {
  /** Umbrella run id. */
  runId: string;
  /** Epoch ms when the mission completed. */
  ts: number;
  /** 0.0–1.0 success score from the supervisor. */
  success: number;
  /** Net revenue in USD generated by this mission. */
  revenueUsd: number;
  /** Short human blurb that appears in the "Proof of Work" ticker. */
  label: string;
};

export type PriceTick = {
  /** Epoch ms. */
  t: number;
  /** Token price in USD. */
  price: number;
};

export type AgentListing = {
  id: string;
  /** Token ticker, e.g. "YIELD". */
  symbol: string;
  /** Human name, e.g. "Yield Reaper". */
  name: string;
  tagline: string;
  category: AgentCategory;
  blueprintId: string;
  /** ERC-8004 agent identity NFT contract + tokenId. */
  identity: { chain: "base"; contract: string; tokenId: string };
  /** ERC-20 labor-backed token, on Base. */
  token: { chain: "base"; address: string; decimals: number };
  /** Uniswap v4 pool + hook responsible for the productivity economics. */
  pool: { id: string; hookAddress: string; tvlUsd: number; volume24hUsd: number };
  price: {
    usd: number;
    change24h: number;
    change7d: number;
    fdvUsd: number;
  };
  /** Labor metrics — these are what the v4 hook reads. */
  performance: {
    missionsTotal: number;
    missions24h: number;
    successRate: number; // 0–1
    revenueAllTimeUsd: number;
    revenue24hUsd: number;
    /** Tokens bought-back-and-burned by the agent from its own earnings. */
    burnedTokens: number;
    /** Live dynamic swap fee set by the hook, in bps (1 bp = 0.01%). */
    dynamicFeeBps: number;
    /** Runway in hours before the agent's Smart Wallet runs dry. */
    runwayHours: number;
    /** Whether the agent is currently executing a mission. */
    active: boolean;
  };
  spark: PriceTick[];
  missions: MissionEvent[];
  /** Unix ms that this listing was last updated by the relayer. */
  updatedAt: number;
  /**
   * Number of times this hook has been forked by other users (via the
   * Marketplace "Fork" flow). Populated by `/api/v1/marketplace` from the
   * `forked_from` column added in migration 0003.
   */
  forksCount?: number;
  /**
   * Pump.fun-style bonding curve metadata. Populated once the launch
   * orchestrator has deployed the curve. Stages:
   *   - "pending"    : launch underway, curve not yet live
   *   - "deploying"  : factory tx seen, curve deploy in progress
   *   - "active"     : curve trading is open
   *   - "graduated"  : threshold crossed; v4 pool is live
   *   - "failed"     : deploy failed, surfaced as deploy_error
   */
  curve?: {
    address: string | null;
    chainId: number | null;
    stage: "pending" | "deploying" | "active" | "graduated" | "failed";
    ethReserveWei: string;
    graduationThresholdWei: string;
    progress: number;
    deployError: string | null;
    verifiedAt: string | null;
  };
};

export type AgentCategoryMeta = {
  id: AgentCategory | "all";
  label: string;
  hint: string;
};

export const CATEGORIES: AgentCategoryMeta[] = [
  { id: "all", label: "All agents", hint: "every worker on umbrella" },
  { id: "yield", label: "Yield", hint: "auto-compounders on Base DeFi" },
  { id: "trading", label: "Trading", hint: "arb + momentum agents" },
  { id: "research", label: "Research", hint: "briefings, scans, intel" },
  { id: "scraper", label: "Scraping", hint: "data extraction workers" },
  { id: "writer", label: "Writers", hint: "copy + briefing synthesis" },
  { id: "security", label: "Security", hint: "contract auditors" },
];

export type SortKey = "momentum" | "revenue" | "price" | "missions" | "new";

export const SORTS: Array<{ id: SortKey; label: string }> = [
  { id: "momentum", label: "Momentum" },
  { id: "revenue", label: "Revenue 24h" },
  { id: "missions", label: "Missions 24h" },
  { id: "price", label: "Price" },
  { id: "new", label: "New" },
];

// ---------------------------------------------------------------------------
// Seed generator — deterministic so the UI is stable across reloads. Builds
// a plausibly noisy price walk and correlates "mission complete" markers with
// small positive jumps.
// ---------------------------------------------------------------------------

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashStr(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function buildSpark(
  seed: number,
  basePrice: number,
  points: number,
  missions: MissionEvent[],
): PriceTick[] {
  const rng = mulberry32(seed);
  const now = Date.now();
  const ticks: PriceTick[] = [];
  let price = basePrice;
  const missionBumps = new Set(
    missions.map((m) => Math.floor(((now - m.ts) / (24 * 60 * 60 * 1000)) * points)),
  );
  for (let i = points - 1; i >= 0; i--) {
    const drift = (rng() - 0.48) * 0.04;
    const bump = missionBumps.has(points - 1 - i) ? 0.01 + rng() * 0.03 : 0;
    price = Math.max(0.0001, price * (1 + drift + bump));
    ticks.push({ t: now - i * (24 * 60 * 60 * 1000) / points, price });
  }
  return ticks;
}

function buildMissions(
  seed: number,
  count: number,
  tone: string[],
): MissionEvent[] {
  const rng = mulberry32(seed);
  const now = Date.now();
  const out: MissionEvent[] = [];
  for (let i = 0; i < count; i++) {
    const hoursAgo = rng() * 24;
    out.push({
      runId: Math.random().toString(16).slice(2, 10),
      ts: now - Math.floor(hoursAgo * 60 * 60 * 1000),
      success: 0.6 + rng() * 0.4,
      revenueUsd: Math.round(rng() * 60 * 100) / 100,
      label: tone[Math.floor(rng() * tone.length)],
    });
  }
  return out.sort((a, b) => b.ts - a.ts);
}

export function seedMarketplace(): AgentListing[] {
  const specs: Array<{
    id: string;
    symbol: string;
    name: string;
    tagline: string;
    category: AgentCategory;
    blueprintId: string;
    basePrice: number;
    successRate: number;
    rev24h: number;
    missions24h: number;
    revAllTime: number;
    active: boolean;
    missionLabels: string[];
  }> = [
    {
      id: "agent-yield-reaper",
      symbol: "REAP",
      name: "Yield Reaper",
      tagline: "Auto-compounds across Aerodrome + Morpho every 5 min",
      category: "yield",
      blueprintId: "auto-compound",
      basePrice: 0.428,
      successRate: 0.97,
      rev24h: 412.38,
      missions24h: 288,
      revAllTime: 86_420,
      active: true,
      missionLabels: [
        "Compound: Aero gauge → vAMM-WETH/USDC",
        "Reinvested 0.0042 ETH into Moonwell cbBTC",
        "Morpho blue · claimed + looped 0.12 stg rewards",
        "Swept dust 14 tokens → USDC",
      ],
    },
    {
      id: "agent-arb-sentinel",
      symbol: "ARBS",
      name: "Arbitrage Sentinel",
      tagline: "Cross-DEX price gaps sub-block on Base",
      category: "trading",
      blueprintId: "base-arb-sentinel",
      basePrice: 1.184,
      successRate: 0.93,
      rev24h: 823.12,
      missions24h: 612,
      revAllTime: 212_900,
      active: true,
      missionLabels: [
        "Arb: SushiV3 → Aerodrome CL · +$3.44",
        "Flash-loan route across 3 pools · +$11.02",
        "Canceled: stale quote, MEV protect tripped",
        "Arb: BaseSwap → UniV4 hook pool · +$1.89",
      ],
    },
    {
      id: "agent-base-pulse",
      symbol: "PULSE",
      name: "Base-Pulse Scribe",
      tagline: "Flags new contract deploys within 60s, generates safety report",
      category: "research",
      blueprintId: "base-pulse-report",
      basePrice: 0.073,
      successRate: 0.89,
      rev24h: 41.2,
      missions24h: 94,
      revAllTime: 9_820,
      active: false,
      missionLabels: [
        "New deploy: 0xA8…f21 · verdict: honeypot",
        "Generated CEO briefing · 128 weekly deploys",
        "Flagged rug risk on 0xC1…ab4 (no renounce)",
        "Clean: legit L2 gaming primitive",
      ],
    },
    {
      id: "agent-social-scribe",
      symbol: "SCRB",
      name: "Alpha Scribe",
      tagline: "Monitors devcommits + feeds into CEO briefings",
      category: "writer",
      blueprintId: "alpha-scribe",
      basePrice: 0.212,
      successRate: 0.91,
      rev24h: 128.77,
      missions24h: 44,
      revAllTime: 34_110,
      active: true,
      missionLabels: [
        "Brief: 'Base devs shipped 312 commits this week'",
        "Weekly letter → 11 subscribers",
        "Compiled intel: Uniswap v4 hook landscape",
      ],
    },
    {
      id: "agent-floor-scraper",
      symbol: "FLOOR",
      name: "Floor Scraper",
      tagline: "Tracks Base NFT floors + signals buy zones",
      category: "scraper",
      blueprintId: "nft-floor-scan",
      basePrice: 0.055,
      successRate: 0.82,
      rev24h: 22.55,
      missions24h: 168,
      revAllTime: 6_140,
      active: true,
      missionLabels: [
        "Scan: Based Punks floor 0.09 ETH (−4.2%)",
        "Alert: sweeper wallet loaded 3 collections",
        "Refreshed 40 collections, 2 failed",
      ],
    },
    {
      id: "agent-audit-hawk",
      symbol: "HAWK",
      name: "Audit Hawk",
      tagline: "Pre-deploy slither + on-chain diff analysis",
      category: "security",
      blueprintId: "contract-audit",
      basePrice: 2.944,
      successRate: 0.98,
      rev24h: 314.1,
      missions24h: 18,
      revAllTime: 98_220,
      active: false,
      missionLabels: [
        "Audit pass: 0xD1…a02 · 0 highs, 2 mediums",
        "Delta vs mainnet: 4 storage slots shifted",
        "Flagged: delegatecall to untrusted proxy",
      ],
    },
  ];

  return specs.map((s) => {
    const seed = hashStr(s.id);
    const missions = buildMissions(seed, 12, s.missionLabels);
    const spark = buildSpark(seed, s.basePrice, 48, missions);
    const priceNow = spark[spark.length - 1].price;
    const price7d = spark[0].price;
    const price24h = spark[Math.floor(spark.length * 0.5)].price;
    const dynamicFeeBps = s.successRate >= 0.95 ? 5 : s.successRate >= 0.85 ? 30 : 100;
    const burned = Math.round(s.revAllTime * 0.35 * 1000);
    return {
      id: s.id,
      symbol: s.symbol,
      name: s.name,
      tagline: s.tagline,
      category: s.category,
      blueprintId: s.blueprintId,
      identity: {
        chain: "base",
        contract: "0xA7e7c7cA9E3AA8B5Dd5EAd9F1cF9A8Ec8F5b5D3A",
        tokenId: String(seed % 100_000),
      },
      token: {
        chain: "base",
        address: `0x${(seed % 0xffffff).toString(16).padStart(6, "0")}${"c0ffee".repeat(6).slice(0, 34)}`,
        decimals: 18,
      },
      pool: {
        id: `0x${(seed * 3).toString(16).slice(0, 16).padStart(16, "0")}`,
        hookAddress: "0xHOOKUmbrellaPerformance000000000000000000",
        tvlUsd: Math.round(priceNow * 1_200_000),
        volume24hUsd: Math.round(s.rev24h * 7.1 * 100) / 100,
      },
      price: {
        usd: priceNow,
        change24h: (priceNow - price24h) / price24h,
        change7d: (priceNow - price7d) / price7d,
        fdvUsd: priceNow * 1_000_000,
      },
      performance: {
        missionsTotal: Math.round(s.revAllTime / 8),
        missions24h: s.missions24h,
        successRate: s.successRate,
        revenueAllTimeUsd: s.revAllTime,
        revenue24hUsd: s.rev24h,
        burnedTokens: burned,
        dynamicFeeBps,
        runwayHours: Math.round(24 + (seed % 60)),
        active: s.active,
      },
      spark,
      missions,
      updatedAt: Date.now(),
    };
  });
}

/**
 * Fill missing market fields for user-forged listings.
 *
 * The public feed is sourced from `generated_hooks` rows, which do not yet
 * have a dedicated on-chain indexer backing price/missions/revenue metrics.
 * This helper gives each listing a deterministic synthetic market profile so
 * UI surfaces (charts, tape, quick-buy routing) stay active and stable until
 * real pool data is wired.
 */
export function enrichListingWithSyntheticMarket(
  listing: AgentListing,
  seedHint = listing.id,
): AgentListing {
  const needsSpark = !Array.isArray(listing.spark) || listing.spark.length < 8;
  const needsPrice = !listing.price.usd || !Number.isFinite(listing.price.usd);
  const needsPerf = !listing.performance.missions24h;
  if (!needsSpark && !needsPrice && !needsPerf) return listing;

  const seed = hashStr(seedHint);
  const tone = listing.category === "trading"
    ? [
        "Route: BaseSwap → Aero CL",
        "Scalp: spread closed +$3.12",
        "Exit: volatility spike",
        "Re-enter: depth normalized",
      ]
    : [
        "Task completed",
        "Model refresh",
        "Liquidity check",
        "Signal emitted",
      ];
  const missions = buildMissions(seed, 10, tone);
  const basePrice = 0.02 + (seed % 4000) / 1000;
  const spark = buildSpark(seed, basePrice, 48, missions);
  const priceNow = spark[spark.length - 1]!.price;
  const price7d = spark[0]!.price;
  const price24h = spark[Math.max(1, Math.floor(spark.length * 0.5))]!.price;
  const successRate = listing.performance.successRate > 0
    ? listing.performance.successRate
    : 0.82 + (seed % 15) / 100;
  const dynamicFeeBps =
    successRate >= 0.95 ? 5 : successRate >= 0.85 ? 30 : 100;

  return {
    ...listing,
    spark,
    missions,
    price: {
      usd: priceNow,
      change24h: (priceNow - price24h) / price24h,
      change7d: (priceNow - price7d) / price7d,
      fdvUsd: Math.max(listing.price.fdvUsd, priceNow * 1_000_000),
    },
    pool: {
      ...listing.pool,
      tvlUsd: Math.max(listing.pool.tvlUsd, Math.round(priceNow * 600_000)),
      volume24hUsd: Math.max(
        listing.pool.volume24hUsd,
        Math.round((listing.performance.revenue24hUsd || 40) * 8 * 100) / 100,
      ),
    },
    performance: {
      ...listing.performance,
      missionsTotal: Math.max(listing.performance.missionsTotal, missions.length * 25),
      missions24h: Math.max(listing.performance.missions24h, missions.length),
      successRate,
      revenueAllTimeUsd: Math.max(listing.performance.revenueAllTimeUsd, missions.length * 120),
      revenue24hUsd: Math.max(
        listing.performance.revenue24hUsd,
        Math.round(missions.reduce((acc, m) => acc + m.revenueUsd, 0) * 100) / 100,
      ),
      burnedTokens: Math.max(
        listing.performance.burnedTokens,
        Math.round(((listing.performance.revenueAllTimeUsd || 1_000) * 0.3) * 100),
      ),
      dynamicFeeBps,
      runwayHours: Math.max(listing.performance.runwayHours, 18 + (seed % 64)),
      active: listing.performance.active || (seed % 3 === 0),
    },
    updatedAt: Date.now(),
  };
}

// ---------------------------------------------------------------------------
// Formatters — kept here so cards and tables render numbers the same way.
// ---------------------------------------------------------------------------

export function formatUsd(n: number, opts: { compact?: boolean } = {}): string {
  if (!Number.isFinite(n)) return "—";
  if (opts.compact) {
    const abs = Math.abs(n);
    if (abs >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
    if (abs >= 1_000) return `$${(n / 1_000).toFixed(1)}K`;
  }
  const digits = Math.abs(n) < 1 ? 4 : 2;
  return `$${n.toFixed(digits)}`;
}

export function formatPct(n: number): string {
  const pct = n * 100;
  const sign = pct > 0 ? "+" : "";
  return `${sign}${pct.toFixed(2)}%`;
}

export function formatNumber(n: number): string {
  if (!Number.isFinite(n)) return "—";
  const abs = Math.abs(n);
  if (abs >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (abs >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toFixed(0);
}

export function timeAgo(ts: number): string {
  const diff = Math.max(0, Date.now() - ts);
  const s = Math.floor(diff / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

export function sortListings(
  listings: AgentListing[],
  key: SortKey,
): AgentListing[] {
  const copy = [...listings];
  switch (key) {
    case "revenue":
      return copy.sort(
        (a, b) => b.performance.revenue24hUsd - a.performance.revenue24hUsd,
      );
    case "missions":
      return copy.sort(
        (a, b) => b.performance.missions24h - a.performance.missions24h,
      );
    case "price":
      return copy.sort((a, b) => b.price.usd - a.price.usd);
    case "new":
      return copy.sort((a, b) => b.updatedAt - a.updatedAt);
    case "momentum":
    default:
      return copy.sort(
        (a, b) =>
          b.price.change24h * b.performance.successRate -
          a.price.change24h * a.performance.successRate,
      );
  }
}
