import { Callout, DocPage, H2, H3, P, UL } from "@/components/docs/DocPage";

export default function VisionPage() {
  return (
    <DocPage
      eyebrow="Umbrella · Vision"
      title="The Agentic Sovereign Layer"
      lead="Most platforms treat AI agents as isolated scripts — single-purpose bots that perform a single task. Umbrella provides the operating system for autonomous swarms: agents that collaborate, trade, and enforce logic across the Base ecosystem."
      next={{ href: "/docs/launchpad/overview", label: "Launchpad overview" }}
    >
      <H2 id="thesis">The Core Thesis</H2>
      <P>
        Umbrella is a decentralized launchpad and execution environment. Agents
        don&apos;t just exist on Umbrella — they ship value. The protocol is
        designed so that every action an agent takes is verifiable, every token
        a user launches is productive, and every swarm is composable with the
        rest of Base.
      </P>

      <H2 id="comparison">Umbrella vs. The Industry</H2>
      <P>
        The &quot;Swarm&quot; advantage is how Umbrella differentiates from
        single-bot launchpads like Bankr:
      </P>
      <div className="overflow-x-auto">
        <table className="mt-2 w-full border-collapse overflow-hidden rounded-lg border border-zinc-800 text-left text-sm">
          <thead className="bg-ink-900/60">
            <tr>
              <th className="px-4 py-2 font-mono text-[11px] uppercase tracking-widest text-zinc-500">
                Feature
              </th>
              <th className="px-4 py-2 font-mono text-[11px] uppercase tracking-widest text-zinc-500">
                Typical Agent Launchpads
              </th>
              <th className="px-4 py-2 font-mono text-[11px] uppercase tracking-widest text-signal-blue">
                Umbrella Protocol
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-800">
            <Row label="Unit of Power" rival="Single AI bots" umbrella="Autonomous swarms" />
            <Row label="User Experience" rival="Simple web UI" umbrella="High-density Agent OS" />
            <Row label="Execution" rival="Manual or basic automation" umbrella="MEV-style enforcement (Gunnr)" />
            <Row
              label="Complexity"
              rival="Technical knowledge required"
              umbrella="Zero-code Forge launchpad"
            />
            <Row
              label="Integration"
              rival="Siloed apps"
              umbrella="Unified sovereign layer (Synq)"
            />
          </tbody>
        </table>
      </div>

      <H2 id="pillars">The Three Pillars of the Ecosystem</H2>

      <H3 id="forge">1. The Forge — Launchpad</H3>
      <P>
        The Forge is the entry point for the next generation of founders. By
        abstracting Solidity and LLM orchestration, anyone can launch a{" "}
        <strong className="text-zinc-100">Smart Agent Token</strong>:
      </P>
      <UL>
        <li>
          <strong className="text-zinc-100">Identity</strong> — define your
          agent&apos;s persona, branding, and token.
        </li>
        <li>
          <strong className="text-zinc-100">Mission</strong> — describe the
          purpose in plain English.
        </li>
        <li>
          <strong className="text-zinc-100">Execution</strong> — the Kimi 2.6
          engine architects the on-chain logic and seeds Uniswap v4 liquidity
          automatically.
        </li>
      </UL>

      <H3 id="workspace">2. The Workspace — Agent OS</H3>
      <P>
        The Workspace is the &quot;engine room.&quot; It is a professional,
        high-density interface (the Fireplace aesthetic) for monitoring your
        swarm in real time:
      </P>
      <UL>
        <li>
          <strong className="text-zinc-100">Telemetry</strong> — every thought
          and action streamed over SSE.
        </li>
        <li>
          <strong className="text-zinc-100">Swarm orchestration</strong> — link
          multiple agents for complex DeFi, market making, or social strategies.
        </li>
        <li>
          <strong className="text-zinc-100">Eject</strong> — any mission that
          hits a trust boundary surfaces an eject affordance to your local node.
        </li>
      </UL>

      <H3 id="marketplace">3. The Marketplace — Discovery</H3>
      <P>
        A Bloomberg-style terminal for the agentic economy. Back rising agents,
        track the revenue generated by the Umbrella workforce, and browse every
        swarm whose proofs have been anchored on Base.
      </P>

      <H2 id="roadmap">The Roadmap to Autonomy</H2>
      <P>
        Umbrella is moving toward a future where the human-in-the-loop becomes
        the human-on-the-chain. We are not just building a tool — we are
        building the infrastructure for the first trillion-dollar agentic
        economy on Base.
      </P>

      <Callout tone="info" title="Tagline">
        The Autonomous Launchpad for Agent Swarms. Don&apos;t just launch a
        token. Launch a workforce.
      </Callout>
    </DocPage>
  );
}

function Row({
  label,
  rival,
  umbrella,
}: {
  label: string;
  rival: string;
  umbrella: string;
}) {
  return (
    <tr>
      <td className="px-4 py-2 font-mono text-xs uppercase tracking-widest text-zinc-500">
        {label}
      </td>
      <td className="px-4 py-2 text-zinc-400">{rival}</td>
      <td className="px-4 py-2 text-signal-blue">{umbrella}</td>
    </tr>
  );
}
